HungryCatsStudio/poly-commit

Cargo.toml
src/ligero/mod.rs

PCS Ligero constructor

---

src/ligero/mod.rs
src/ligero/tests.rs
src/ligero/utils.rs

Had to change some trait bounds regarding `C::Leaf` so that we can use e.g. Pedersen or Sha256 hashing.
Expect one test to fail, since the `trim()` function panics with `todo()`
---

Add first tests for setup of LigeroPCS

---

Cargo.toml
src/ligero/mod.rs

Potentially we still need to add these params to `UniversalParams` -> and figure out how we construct these in `UniversalParams`. Alternatively, we skip calling setup all together and just construct the correct vk/ck from the hash params.
---

Params trait bounds

---

src/ligero/mod.rs
src/ligero/utils.rs

Open and check

---

src/ligero/mod.rs

changed access to params

---

src/ligero/tests.rs
src/ligero/utils.rs

Fix matrix `new_from_flat`

---

src/ligero/data_structures.rs
src/ligero/mod.rs
src/ligero/utils.rs

Refactor prover

---

src/ligero/mod.rs
src/ligero/tests.rs

Merkle Tree construction fix

---

src/ligero/mod.rs
src/ligero/tests.rs

Transcript construction and loops are fixed, added some tests for `open` and `check`
---

Opening and check fixes

---

src/ligero/data_structures.rs
src/ligero/mod.rs
src/ligero/tests.rs
src/ligero/utils.rs

Main functionality test passing with the new RS. Dimension computation fixed.
---

Main functionality test passing with the new RS

---

src/error.rs
src/lib.rs
src/ligero/data_structures.rs
src/ligero/mod.rs
src/ligero/tests.rs
src/ligero/utils.rs

We allow the well-formedness checks to be optional - and in the case where we have them, the same set of indices is used for the columns, thus saving communication (and verification) costs, as per Brakedown paper optimization.
---

Well-formedness checks refactor

---

src/ligero/mod.rs
src/ligero/tests.rs
src/ligero/utils.rs

It is more efficient to just call FFT on the coefficients directly.
---

Change encoding function

---

src/lib.rs
src/ligero/data_structures.rs
src/ligero/mod.rs
src/ligero/tests.rs
src/ligero/utils.rs

Also some other minor fixes and documentation
closes: #XXXX
---

Bring in remaining tests from the test suite

---

src/ligero/data_structures.rs
src/ligero/mod.rs
src/ligero/tests.rs
src/ligero/utils.rs

Fix `todo()`; Move `Ligero` implementation to data_structures; minor clippy lints

---

Cargo.toml
src/ligero/data_structures.rs
src/ligero/mod.rs
src/ligero/utils.rs

no-std compat

---

bench-templates/src/lib.rs
poly-commit/benches/hyrax_times.rs

Hyrax fix bench

---

bench-templates/src/lib.rs
poly-commit/benches/brakedown_ml_times.rs

Brakedown fix bench

---

bench-templates/src/lib.rs
poly-commit/benches/ligero_ml_times.rs

Ligero fix benches

---

poly-commit/Cargo.toml
poly-commit/src/hyrax/mod.rs

hyrax before:
`commit Hyrax254/20      time:   [1.0561 s 1.0618 s 1.0686 s]`
hyrax with parallel commits per column:
`commit Hyrax254/20      time:   [534.62 ms 534.97 ms 535.31 ms]`
Benched on 16 cores / 32 threads. The effect is smaller than what we saw for other PCS (was it 70% reduction for Ligero IIRC?), but still quite significant compared to the non-parallel version.
---

Hyrax parallel `commit`

---

poly-commit/src/hyrax/data_structures.rs
poly-commit/src/hyrax/mod.rs

As discussed, I have reverted back to its original definition by removing the evaluation-commitment randomness from the proof and ignoring the claimed-value argument in check. Tests pass.
---

Make Hyrax hiding again

---

poly-commit/src/linear_codes/mod.rs

I was testing out your branch and noticed unrelated potential improvements.
This is not noticeable in our benchmarks which only have one polynomial/commitment/state, but I expect that there will be a slight space saving when working with multiple polys, as we would avoid explicit casts and I think as a consequence clones.
---

Brakedown+++

---

poly-commit/src/linear_codes/mod.rs
poly-commit/src/linear_codes/utils.rs
poly-commit/src/utils.rs

This PR is just for discussion regarding this change.
---

Remove `IOPTranscript`

---

poly-commit/benches/hyrax_times.rs
poly-commit/src/hyrax/mod.rs
poly-commit/src/hyrax/tests.rs
poly-commit/src/utils.rs

Just a PR for code review.
---

Delete `IOPTranscript` for Hyrax

---

poly-commit/src/linear_codes/ligero.rs
poly-commit/src/linear_codes/mod.rs
poly-commit/src/linear_codes/univariate_ligero/tests.rs
poly-commit/src/linear_codes/utils.rs
poly-commit/src/utils.rs

Delete `IOPTranscript` for Ligero

---

poly-commit/src/linear_codes/brakedown.rs
poly-commit/src/linear_codes/utils.rs
poly-commit/src/utils.rs

only enable num-traits on `target_arch = "aarch64"`

---

poly-commit/src/streaming_kzg/mod.rs

Introduced by https://github.com/arkworks-rs/algebra/pull/843

Fix breaking change from algebra/poly
